### ISSUE TITLE
Provide an example on how to loop over an array in json

### ISSUE THREAD

**Issue by m42e** [joshuafontany/TW5-JsonMangler#11]
Hi,

I have a path in json, which contains an array. I want to loop over this array. 
Is there any tutorial or idea how to do this?

Thanks.

**Comment by joshuafontany** [comment]
Hi m42e,

I have an update to the indexes[] filter ready to go that allows you to give it a path, & also a suffix flag that grabs the 'root' or immediate index names from the given tiddler or sub path. That should do it for you. Need to run a couple more test cases, but it should be ready later today.

Best, Joshua

**Comment by m42e** [comment]
Thanks a lot, if there is anything I could do, let me know. I‘m not too much into JS to be honest

**Comment by joshuafontany** [comment]
Hi! I found and squashed a few bugs, but this has been released.

See the announcement at: https://groups.google.com/forum/#!topic/tiddlywiki/z9DjVvm3Q1M

Best,
Joshua F

**Comment by joshuafontany** [comment]
Hi. I found a bug in the node.js server install package, and also decided to change the flag syntax. Please see the new announcement: https://groups.google.com/d/msg/tiddlywiki/z9DjVvm3Q1M/eUWGTtBDBgAJ

**Comment by m42e** [comment]
Thanks for your support.
