### ISSUE TITLE
CSV Import to tiddler error

### ISSUE THREAD

**Issue by AnthonyMuscio** [joshuafontany/TW5-JsonMangler#20]
Joshua,

I have always treasured the availability of the JSON plugin and I thank you for responding to my previous requests in relation to CSVs.

I am importing a CSV file at the moment and getting an errors converting them to tiddlers, I downloaded your whole wiki at https://chronicles.wiki/TW5-JsonMangler/ to ensure I had the full package. I note its on the Pre-release (at some point in time).

When I hit import I get the following;

```
Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: $tw.utils.slugifyText is not a function
```

I would be happy to share the csv tiddler "privately" if it may help trouble shooting, but I expect it has something to do with the new slugify features.

Regards
Tony

**Comment by joshuafontany** [comment]
Hi Tony,

Good catch! This is definitely a bug. Looks like I missed removing one of the calls to my custom "slugifyText" code.

The core now has the "slugify[]" operator, and the portion of CSV import code should reference that or the $tw.utils.* function used in that filter operator. I will get a new version & demo wiki up for you asap once this is fixed.

Mahalo (thanks),
Joshua F

**Comment by AnthonyMuscio** [comment]
A big Thanks Joshua. 

I am big on open source and your contributions are extensive, however I am using this today for my Partners Business, as I always expected JSON mangler to be a key tool for bigger data needs this was inevitable. Do you have a donations channel? although only small I would like to make a donation.

FYI so you know how I am using it, I need to add hundreds of keywords to 50 products in WooCommerce Exporting the relevant products and converting them to tiddlers allows full use of the tiddlywiki UI for tagging and generating a key word list, that can then be copy and paste back to the product definitions SEO, Perhaps one day even the last step can be automated. After this there are still another hundred products. https:/LaSource.com.au

Thanks
Tony

**Comment by AnthonyMuscio** [comment]
Joshua is it possible for me to access a prior version that may not have this problem?

I need to convert the data now.

Regards
Tony

**Comment by joshuafontany** [comment]
Hey Tony,

Sorry about the delay. Yes, grab one of my past Releases, and use it with the 5.1.22 TW release:

https://github.com/joshuafontany/TW5-JsonMangler/releases/tag/v2.2.2

That one should have the correct $tw.util function and not error out on you.

Best,
Joshua F

**Comment by AnthonyMuscio** [comment]
Joshua,

Thanks for your help. I have never installed plugins via node before, I am using bob.exe 

But I found an earlier install

Tony

**Comment by joshuafontany** [comment]
Hi Tony,

I have fixed this issue, and there is a new Demo Wiki up that works as designed when importing CSV tiddlers into regular or Json Tiddlers. You should be able to now drag/drop from there into any 5.1.23-pre TW instance.

Thanks for the bug report & the donation. Much appreciated!

Best,
Joshua F

**Comment by AnthonyMuscio** [comment]
Joshua,

Thanks and you are welcome.

JSON mangler is that tool that sits in the background for me but when I need it  is essential. Thanks for such a comprehensive solution.

It is fantastic as a utility wiki, where its is installed for the refactoring of data importing to exporting then drag and drop on the wiki using the results.

Of course some serious solution my include it in a production wiki as well.

It would make sense to release an edition, not unlike the demo site, people can download the whole wiki  as needed. It would be appropriate to add it to the core editions file:///C:/Data/TW5/!TiddlyWiki.com/tiddlywiki.com.html#Editions

Regards
Tony
