### ISSUE TITLE
Search on Json

### ISSUE THREAD

**Issue by oxydum** [joshuafontany/TW5-JsonMangler#5]
Hi Joshua,

I'm looking for a way to retrieve data from keys like in this myjson:

`[{"key":10,val:"A"},{"key":11,val:"B"},{"key":12,val:"C"}]`

`<<search key="11">> to retrieve "B"`
I know to get this by rank : `{{myjson##/1/val}}`

Thanks

**Comment by joshuafontany** [comment]
Hmmm, great question.  It took me a couple of read-throughs to fully understand your query.

One thing to note. JSON sytax requires all key-names to be strings (wrapped in quotes). Your `val` keys should be `"val"`.

tOk, so The first way I would approach it is a macro with some $list widget action.


```
\define searchKeyArray(keyName)
<$list filter="[<currentTiddler>indexes[]suffix[key]]" variable="index">
<$list filter="[<currentTiddler>getindex<index>regexp[$keyName$]]" variable="selectedItem">

keyPath = <<index>>

<$list filter="[<index>removesuffix[key]addsuffix[val]]" variable="valPath">

valPath = <<valPath>>

val = {{{ [<currentTiddler>getindex<valPath>] }}}


/* More wikitext here that will let you set the pulled value to another temporary tiddler, or otherwise manipulate this specific index. */

</$list>
</$list>
</$list>
\end

<$tiddler tiddler="TestJson">
<<searchKeyArray keyName:"11">>
</$tiddler>
```

I have tested this in my demo wiki and it works out pretty well. Let me know if that is helpful, and thanks for the question!
