### ISSUE TITLE
Tiddler dropdown menu entries get their width/hoverable area shrunken

### ISSUE THREAD

**Issue by ylh** [joshuafontany/TW5-JsonMangler#6]
See this before/after when activating `jsonmangler`:

<img width="399" alt="Screenshot 2019-05-25 at 11 14 19" src="https://user-images.githubusercontent.com/9125590/58373273-4d875680-7ee0-11e9-9f0d-f61340c6e3d0.png">
<img width="377" alt="Screenshot 2019-05-25 at 11 15 09" src="https://user-images.githubusercontent.com/9125590/58373272-4d875680-7ee0-11e9-9f68-9d7bd95afa0f.png">

By all accounts, this seems to result from the `width: auto` in [ui/controlpanel/packplugin/style.tid:51](https://github.com/joshuafontany/TW5-JsonManglerPlugin/blob/1abd45ddc75f65c435cdce9746cebf9b85655f27/ui/controlpanel/packplugin/style.tid#L51).

Since I haven't fully grasped the various features of this plugin and how these files interact with one another, I cannot confidently say how to fix this (e.g. suggest killing that line) in a way that wouldn't break anything; otherwise, this would be a PR rather than an issue. Nonetheless, I saw fit to bring this to attention.

**Comment by joshuafontany** [comment]
Mahalo (thanks) for catching this! Should be fixed in 2.0.6 (requires TW5.1.20). I changed it to the 'default' `width: 100%`. You get advanced notice of the new Release! (Closed)
