### ISSUE TITLE
Example page is down

### ISSUE THREAD

**Issue by glasmasin** [joshuafontany/TW5-JsonMangler#7]
https://joshuafontany.github.io/TW5-JsonManglerPlugin/ returns a 404

**Comment by joshuafontany** [comment]
Thanks for catching this! Looks like I had been working from an old copy of the ReadMe. The correct link is https://joshuafontany.github.io/TW5-JsonMangler/. Fixed in 2.0.6!

You get advanced notice of the new release! ;)
